using SpeedyWeatherEmulator
using Random
using Plots, CairoMakie


### Prepare emulator evaluation

# Fix the seed for reproducibility
Random.seed!(1234)

# Define simulation parameters and load/format simulation data generated by "generate_data.jl"
#   (we assume raw_data already exists, created by "1_hyperparameter_optimization")
const TRUNC = 5
const N_DATA = 48
const N_IC = 1000

sim_para_loading_data = SimPara(trunc=TRUNC, n_data=N_DATA, n_ic=N_IC)
sim_data = load_data(sim_para_loading_data, type="sim_data")
fd = FormattedData(sim_data)

# Loading the best emulator from the hyperparameter optimiaztion
sim_para_emulator = SimPara(trunc=TRUNC, n_data=N_DATA, n_ic=N_IC, id_key="_hyperpara_L1_W1024")
em = load_data(sim_para_emulator, type="emulator")

# Define container for rel. errors for different forecast lengths
err_vec = zeros(N_DATA)             # rel. errors of trained emulator
err_vec0 = zeros(N_DATA)            # rel. errors of idendity emulator (em(vor) = vor)


# Calculate the rel. errors 
for steps in 1:N_DATA
    err_vec[steps] = compare_emulator(  em,
                                        x_test=fd.data_pairs.x_test,
                                        y_test=fd.data_pairs.y_test,
                                        n_it=steps)
    err_vec0[steps] = compare_emulator( em,
                                        x_test=fd.data_pairs.x_test,
                                        y_test=fd.data_pairs.y_test,
                                        n_it=steps,
                                        id_em=true)     # identy emulator (em(vor) = vor)
end



### Plots of rel. errros

# Plot just the rel. error
p1 = Plots.scatter( err_vec;                     
                    title="Emulator Comparison to Identiy for Long Forecasts",
                    xlabel="Forecast length / h",
                    ylabel="Rel. forecast error / %",
                    legend=false,
                    xticks = ([1,3,6,12,24,48], ["1", "3", "6", "12", "24", "48"]),
                    xformatter = x -> "$(Int(round(x/1e5)))×10⁵",
                    plot_titlefontsize=25,              # title size
                    guidefont=13,                       # axis title size
                    tickfont=12,                        # tick size
                    legendfontsize=12,                  # legend size
                    markersize=5)                       # marker size     

# Plot comparing the trained emulator and the identiy emulator on log-axes
p2 = Plots.scatter( [err_vec, err_vec0];
                    label=["Emulator" "Identity"],
                    title="Emulator Comparison to Identiy for Long Forecasts",
                    xlabel="Forecast length / h",
                    ylabel="Rel. forecast error / %",
                    yscale=:log10, 
                    yticks = ([10,100,1000], ["10", "10²", "10³"]),
                    xticks = ([1,3,6,12,24,48], ["1", "3", "6", "12", "24", "48"]),
                    plot_titlefontsize=25,              # title size
                    guidefont=13,                       # axis title size
                    tickfont=12,                        # tick size
                    legendfontsize=12,                  # legend size
                    markersize=5,                       # marker size
                    legend=:bottomright)

# Display and save plots
display(p1)
display(p2)
Plots.savefig(p1, joinpath(@__DIR__, "plots", "long_forecast_quality.pdf"))
Plots.savefig(p2, joinpath(@__DIR__, "plots", "long_forecast_comp_id.pdf"))


### Heatmap plots for comparison

# Define the time horizons for comparison and used initial condition
horizons = [1, 6, 24, 48]
ic = 9


# Loop for different time horizons
for h in horizons
    # Initial vorticity
    vor0 = sim_data.data[:, 1, ic]

    # Target (SpeedyWeather.jl) and emulated vorticity
    vor_sw = sim_data.data[:, h, ic]
    vor_em = vor0

    for _ in 1:h
        vor_em = em(vor_em)
    end

    # Create heatmap plots
    fig_sw = plot_heatmap(vor_sw, trunc=5, title="")
    fig_em = plot_heatmap(vor_em, trunc=5, title="")

    # Display the figures
    display(fig_sw)
    display(fig_em)

    # Save the plots
    CairoMakie.save(joinpath(@__DIR__, "plots", "sw_$(ic)_$h.pdf"), fig_sw)
    CairoMakie.save(joinpath(@__DIR__, "plots", "em_$(ic)_$h.pdf"), fig_em)
end



