using SpeedyWeatherEmulator
using Random
using Plots, CairoMakie
using FileIO, MosaicViews

### Prepare emulator evaluation


## Prepare emulator

# Fix the seed for reproducibility
Random.seed!(1234)

# Define simulation parameters and load/format simulation data generated by "generate_data.jl"
#   (we assume raw_data already exists, created by "1_hyperparameter_optimization")
const TRUNC = 5
const N_DATA = 48
const N_IC = 1000

sim_para_loading = SimPara(trunc=TRUNC, n_data=N_DATA, n_ic=N_IC)
sim_data = load_data(sim_para_loading, type="sim_data")
fd = FormattedData(sim_data)

# Loading the emulator
#   (we assume a trained emulator already exists, created by "2_long_forecast_quality")
# sim_para_emulator = SimPara(trunc=TRUNC, n_data=N_DATA, n_ic=N_IC, id_key="_fq")
# em = load_data(sim_para_emulator, type="emulator")

### DELETE LATER
sim_para_emulator = SimPara(trunc=TRUNC, n_data=N_DATA, n_ic=N_IC, id_key="_hyperpara_L1_W1024")
em = load_data(sim_para_emulator, type="emulator")
### DELETE LATER


## Prepare test data

# Define Rossby-Haurwitz wave
m = 4
ω = 7.848e-6
K = 7.848e-6

ζ(λ, θ, σ) = 2ω*sind(θ) - K*sind(θ)*cosd(θ)^m*(m^2 + 3m + 2)*cosd(m*λ)

# Define test data
sim_para_RH = SimPara(trunc=5, n_data=48, n_ic=1, initial_cond=ζ, id_key="_RH_wave")
generate_raw_data(sim_para_RH)
sim_data_RH = SimData(sim_para_RH)
fd_RH = FormattedData(sim_data_RH, splits=(train=0, valid=0, test=1))


## Calculate rel. errors

# Define container for rel. errors for different forecast lengths
err_vec = zeros(N_DATA)             # rel. errors of trained emulator
err_vec0 = zeros(N_DATA)            # rel. errors of idendity emulator (em(vor) = vor)


# Calculate the rel. errors 
for steps in 1:N_DATA
    err_vec[steps] = compare_emulator(  em,
                                        x_test=fd_RH.data_pairs.x_test,
                                        y_test=fd_RH.data_pairs.y_test,
                                        n_it=steps)
    err_vec0[steps] = compare_emulator( em,
                                        x_test=fd_RH.data_pairs.x_test,
                                        y_test=fd_RH.data_pairs.y_test,
                                        n_it=steps,
                                        id_em=true)
end



### Plots of rel. errros

# Plot just the rel. error
Plots.scatter(err_vec)
Plots.scatter(err_vec0)

# Plot comparing the trained emulator and the identiy emulator on log-axes
Plots.scatter(err_vec, yscale=:log10)
Plots.scatter!(err_vec0, yscale=:log10)



### Heatmap plots for comparison

# Define the time horizons for comparison
horizons = [1, 6, 24, 48]


# Loop for different time horizons
for h in horizons
    # Initial vorticity
    vor0 = sim_data_RH.data[:, 1, 1]

    # Target (SpeedyWeather.jl) and emulated vorticity
    vor_sw = sim_data_RH.data[:, h, 1]
    vor_em = vor0

    for _ in 1:h
        vor_em = em(vor_em)
    end

    # Create heatmap plots
    fig_sw = plot_heatmap(vor_sw, trunc=5, title="speedyweather: $h")
    fig_em = plot_heatmap(vor_em, trunc=5, title="emulator: $h")

    display(fig_sw)
    display(fig_em)


    # Create output path 
    outpath_sw = joinpath(@__DIR__, "plots", "sw_$h.png")
    outpath_em = joinpath(@__DIR__, "plots", "em_$h.png")

    # Save the plots
    CairoMakie.save(outpath_sw, fig_sw)
    CairoMakie.save(outpath_em, fig_em)
end

# Load the plots and combine them 
img_sw = [load(joinpath(@__DIR__, "plots", "sw_$h.png")) for h in horizons]
img_em = [load(joinpath(@__DIR__, "plots", "em_$h.png")) for h in horizons]
imgs = vcat(img_sw, img_em) 

# Combine the heatmap plots and save the grid-plot for "first look" 
#   (the plots are later combined in another program (inkscape) for better looking plots)
grid = mosaic(imgs; nrow=length(horizons), ncol=2)
save(joinpath(@__DIR__, "plots", "_grid.png"), grid)
